### ISSUE TITLE
domain endings other than .com

### ISSUE THREAD

**Issue by mingusmoonwalk** [viccherubini/get-shit-done#46]
Sadly, "get-shit-done" does not work with domain endnings other than ".com". For example, there is no way to block "lemonde.fr".

Could you do something about this?

I need it badly :-) Thanks!

**Comment by sim590** [comment]
@mingusmoonwalk Your issue is not accurate. Domains like `.org` are blocked with success. For instance, `archlinux.org` can be blocked. However, I have the same problem, i.e I cannot block `lemonde.fr` for some reason even though, the following lines are in the `/etc/hosts` file after running the script:

```
127.0.0.1	lemonde.fr
127.0.0.1	www.lemonde.fr
```

I'm looking for the explanation.

**Comment by sim590** [comment]
Actually, it has nothing to do with domains. I think that what you (and I) were experiencing is the fact that the browser uses its cache to recover the website's IP address. I guess that you should have figured it out by now (after 4 years). The script correctly appends the correct lines to `/etc/hosts` so there is no reason to keep this open.

@viccherubini I think tha tthis issue should be closed.
